[workspace]
resolver = "3"
members = ["tests/color", "tests/renderer"]

[workspace.package]
edition = "2024"
rust-version = "1.98"
license = "GPL-3.0-or-later"

[workspace.dependencies]
half = { version = "2", features = ["bytemuck"] }
lcms2 = "6"
libheif-rs = "2"
naga = { version = "30", features = ["wgsl-in", "glsl-out"] }
wgpu = "30"
pollster = "1"
bytemuck = { version = "1", features = ["derive"] }
